version: '3'

services:
  fusionpbx:
    build: .
    image: crazyquark/fusionpbx:armhf
    volumes:
      - fusionpbx:/var/www/fusionpbx
    ports:
      - "5060:5060/udp"
      - "9090:80"
      - "9094:443"
    networks:
      main:
        aliases: 
          - fusion
    depends_on:
      - db
  db:
      image: postgres:alpine
      user: "0:0"
      environment:
        POSTGRES_DB: 'fusionpbx'
        POSTGRES_USER: 'fusionpbx'
        POSTGRES_PASSWORD: 'doAvJVVEqkZTXdHYJ7wpCPNLqS7Db7RR'
      volumes:
        - fusionpbx_db:/var/lib/postgresql/data
      networks:
        main:
          aliases:
            - db
networks:
  main:

volumes: 
  fusionpbx_db:
  fusionpbx: