version: '3'

services:
  fusionpbx:
    image: crazyquark/fusionpbx
    ports:
      - "5060:5060/udp"
      - "80:80"
      - "443:443"
    networks:
      main:
        aliases: 
          - fusion
    depends_on:
      - db
  db:
      image: postgres:10-alpine
      user: "0:0"
      environment:
        POSTGRES_DB: 'fusionpbx'
        POSTGRES_USER: 'fusionpbx'
        POSTGRES_PASSWORD: 'doAvJVVEqkZTXdHYJ7wpCPNLqS7Db7RR'
      volumes:
        - fusionpbx_db:/var/lib/postgresql/data
        - fusionpbx_config:/etc/fusionpbx
      networks:
        main:
          aliases:
            - db
networks:
  main:

volumes: 
  fusionpbx_db:
  fusionpbx_config: