version: '3'

services:
  fusionpbx:
    image: crazyquark/fusionpbx
    ports:
      - "5060:5060/udp"
      - "80:80"
      - "443:443"
    networks:
      main:
        aliases: 
          - fusion
    depends_on:
      - db
  db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: 'cTFCkcL3XruJ6XCUxSLy7G-i7qUpzqrQ'
        MYSQL_ROOT_HOST: '0.0.0.0'
        MYSQL_DATABASE: 'fusionpbx'
        MYSQL_USER: 'fusionpbx'
        MYSQL_PASSWORD: 'doAvJVVEqkZTXdHYJ7wpCPNLqS7Db7RR'
      volumes:
        - fusionpbx_db:/var/lib/mysql/
        - fusionpbx_config:/etc/fusionpbx
      networks:
        main:
          aliases:
            - db
networks:
  main:

volumes: 
  fusionpbx_db:
  fusionpbx_config: